services:
  discord-bot:
    build: .
    container_name: BotTo327
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - role_data:/app/data

volumes:
  role_data: